// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp2h44Ng0QUXkOw-LokeYeHbuaGxp6fjM',
    appId: '1:654395225254:web:3458b69d1ca4e63480b067',
    messagingSenderId: '654395225254',
    projectId: 'firebare-flutter-remote-config',
    authDomain: 'firebare-flutter-remote-config.firebaseapp.com',
    storageBucket: 'firebare-flutter-remote-config.appspot.com',
    measurementId: 'G-XGHTTF4WDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKm9UrMcllx6NQmnZS12dhSRkgxX_zdDo',
    appId: '1:654395225254:android:b1257fea2186543480b067',
    messagingSenderId: '654395225254',
    projectId: 'firebare-flutter-remote-config',
    storageBucket: 'firebare-flutter-remote-config.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnxlOruLQ-yp6KdJD2u9ZG7P2xitbnVwU',
    appId: '1:654395225254:ios:167d997c2aa3519a80b067',
    messagingSenderId: '654395225254',
    projectId: 'firebare-flutter-remote-config',
    storageBucket: 'firebare-flutter-remote-config.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseRemoteConfig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnxlOruLQ-yp6KdJD2u9ZG7P2xitbnVwU',
    appId: '1:654395225254:ios:8f8009390a98076d80b067',
    messagingSenderId: '654395225254',
    projectId: 'firebare-flutter-remote-config',
    storageBucket: 'firebare-flutter-remote-config.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseRemoteConfig.RunnerTests',
  );
}
